[SkyMarshal] Remove nullptr dereference in decltypes
This isn't actually a bug, but declval is more idiomatic and doesn't
trip up the nonnull warnings.

Fixes the following build error with GCC 11:

    In file included from bazel-out/nocpu-fastbuild-ST-cadbd3d7f0f9/bin/.../test_types/alpha/alpha_lcm/cpp/lcmtypes/alpha/eigen_type_t.hpp:16,
                     from .../lcm_reflection_test.cc:13:
    bazel-out/k8-fastbuild/bin/.../lcm/_virtual_includes/lcm_reflection/lcm/lcm_reflection.hpp: In instantiation of 'uint32_t lcm::translate_fields(const char* const*, uint32_t*, uint32_t) [with T = std::array<eigen_lcm::Vector2d, 2>; typename std::enable_if<is_iterable_v<T>, bool>::type <anonymous> = true; uint32_t = unsigned int]':
    bazel-out/nocpu-fastbuild-ST-cadbd3d7f0f9/bin/.../test_types/alpha/alpha_lcm/cpp/lcmtypes/alpha/eigen_type_t.hpp:160:88:   required from here
    bazel-out/k8-fastbuild/bin/.../lcm/_virtual_includes/lcm_reflection/lcm/lcm_reflection.hpp:149:87: error: 'this' pointer is null [-Werror=nonnull]
      149 |         translate_fields<std::remove_reference_t<decltype((*static_cast<T *>(nullptr))[0])>>(
          |                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
    In file included from .../include/c++/11.5.0/tuple:39,
                     from .../include/c++/11.5.0/bits/unique_ptr.h:37,
                     from .../include/c++/11.5.0/memory:76,
                     from external/fmt/include/fmt/format.h:39,
                     from .../lcm_reflection_test.cc:1:
    .../include/c++/11.5.0/array:186:7: note: in a call to non-static member function 'constexpr std::array<_Tp, _Nm>::value_type& std::array<_Tp, _Nm>::operator[](std::array<_Tp, _Nm>::size_type) [with _Tp = eigen_lcm::Vector2d; long unsigned int _Nm = 2; std::array<_Tp, _Nm>::reference = eigen_lcm::Vector2d&; std::array<_Tp, _Nm>::size_type = long unsigned int]'
      186 |       operator[](size_type __n) noexcept
          |       ^~~~~~~~

Signed-off-by: Brian Kubisiak <brian.kubisiak@skydio.com>
GitOrigin-RevId: a12e0393a18fd9fbbccbf581638be56f0797b8a3